### ISSUE TITLE
A question on initilization

### ISSUE THREAD

**Issue by cedricbahirwe** [aheze/Setting#1]
Hey @aheze , Great package, Can wait to make a PR ✨

I just had a small question: 

I've seen that in many places throughout the project,  You're initializing **structs** with default argument value identical to the struct's properties' default values. I wanted to know if there's any particular reason for this?

```swift
public struct PreviewConfiguration {
    public var icon: SettingIcon?
    public var indicator = "chevron.forward"
    public var horizontalSpacing = CGFloat(12)
    public var verticalPadding = CGFloat(14)
    public var horizontalPadding = CGFloat(16)

    public init(
        icon: SettingIcon? = nil,
        indicator: String = "chevron.forward",
        horizontalSpacing: CGFloat = CGFloat(12),
        verticalPadding: CGFloat = CGFloat(14),
        horizontalPadding: CGFloat = CGFloat(16)
    ) {
        self.icon = icon
        self.indicator = indicator
        self.horizontalSpacing = horizontalSpacing
        self.verticalPadding = verticalPadding
        self.horizontalPadding = horizontalPadding
    }
}
```

**Comment by aheze** [comment]
Ah yeah. So what happens is that when you make a Swift Package or framework, you need to implement your own `init()` method. The default memberwise struct init isn't available — see this [Stack Overflow question](https://stackoverflow.com/questions/26224693/how-can-i-make-the-memberwise-initialiser-public-by-default-for-structs-in-swi).

The reason why you see so many duplicate values is because I'm using Xcode's "Generate Memberwise Initializer" feature:

<img width="912" alt="Screenshot 2023-02-23 at 3 14 50 PM" src="https://user-images.githubusercontent.com/49819455/221052738-3ffdac6a-ae6c-4c6c-bb81-1773bc04e239.png">

**Comment by cedricbahirwe** [comment]
Yes, I'm aware of that Xcode generation feature, if we have the same values in the initializers, would it make sense to remove them from the default values of the properties and only keep the ones in the memberwise initializers?

For example, someone (I don't know who), might be tempted to update the property value directly instead of updating the default argument value from the initializer.

What I have in my mind is :
```swift
public struct PreviewConfiguration {
    public var icon: SettingIcon?
    public var indicator: String
    public var horizontalSpacing: CGFloat
    public var verticalPadding: CGFloat
    public var horizontalPadding: CGFloat

    public init(
        icon: SettingIcon? = nil,
        indicator: String = "chevron.forward",
        horizontalSpacing: CGFloat = CGFloat(12),
        verticalPadding: CGFloat = CGFloat(14),
        horizontalPadding: CGFloat = CGFloat(16)
    ) {
        self.icon = icon
        self.indicator = indicator
        self.horizontalSpacing = horizontalSpacing
        self.verticalPadding = verticalPadding
        self.horizontalPadding = horizontalPadding
    }
}
```
